/**
 * The pieces the three codegen scripts must agree on, byte for byte.
 *
 * `codegen.mts` writes the trees, `codegen-check.mts` proves them current offline,
 * and `codegen-verify.mts` asks the engine whether they are still semantically
 * right. All three walk the same directories, hash the same sources the same way,
 * and read the same sidecar — and any disagreement between them shows up as a
 * false verdict rather than an error, so the agreement lives here rather than
 * being restated in each script.
 *
 * Nothing here touches the network, `process.env`, or the SDK client: the check
 * has to stay runnable in CI with no API key.
 */
import { createHash } from "node:crypto";
import { readdir, readFile } from "node:fs/promises";
import path from "node:path";
import process from "node:process";

import { isStampableArtifactPath, type CodegenTreeFile, type MthdsFileItem } from "@pipelex/sdk";

export const REPO_ROOT = process.cwd();
export const METHODS_DIR = path.join(REPO_ROOT, "methods");
export const GENERATED_ROOT = path.join(REPO_ROOT, "src", "generated");

/**
 * The lock filename the codegen API emits (`lock_filename` on the response).
 *
 * `codegen.mts` still writes the lock at whatever name the server returns — the
 * tree is verbatim — while the offline check looks for it here. If those two ever
 * disagree the check reports "no lock" and lists what it did find, which makes a
 * rename obvious instead of silent.
 */
export const LOCK_FILENAME = "codegen.lock";

/** The starter-owned staleness sidecar, written beside each lock. Not stamped, not locked. */
export const SOURCES_SIDECAR = "sources.json";

export const SIDECAR_COMMENT =
  "Generated by `npm run codegen`. SHA-256 of every .mthds source in this method's " +
  "closure, so the offline check can tell you to regenerate after a bundle edit. " +
  "Not part of the codegen lock — do not hand-edit.";

/** Sidecar shape — deliberately plain, so a human diff reads as "which bundle changed". */
export interface SourcesSidecar {
  comment: string;
  sources: Record<string, string>;
}

export interface MethodClosure {
  /** Directory name under `methods/`, reused as the generated tree's directory name. */
  name: string;
  /** Every `.mthds` file in the closure, sorted, with repo-relative `source` labels. */
  files: MthdsFileItem[];
  /** Repo-relative path → SHA-256 of the file's bytes, for the sidecar. */
  sourceHashes: Record<string, string>;
}

/** Recursively collect file paths under `dir`, relative to it, sorted for determinism. */
export async function walk(dir: string, prefix = ""): Promise<string[]> {
  const entries = await readdir(dir, { withFileTypes: true });
  const found: string[] = [];
  for (const entry of entries) {
    // Forward slashes: these become artifact paths and sidecar keys, on every platform.
    const relative = prefix ? `${prefix}/${entry.name}` : entry.name;
    if (entry.isDirectory()) {
      found.push(...(await walk(path.join(dir, entry.name), relative)));
    } else if (entry.isFile()) {
      found.push(relative);
    }
  }
  return found.sort();
}

export function sha256(content: string): string {
  return createHash("sha256").update(content, "utf8").digest("hex");
}

/** Discover every method directory under `methods/` and read its `.mthds` closure. */
export async function discoverMethods(): Promise<MethodClosure[]> {
  const entries = await readdir(METHODS_DIR, { withFileTypes: true });
  const methods: MethodClosure[] = [];

  for (const entry of entries
    .filter((e) => e.isDirectory())
    .sort((a, b) => a.name.localeCompare(b.name))) {
    const methodDir = path.join(METHODS_DIR, entry.name);
    const bundlePaths = (await walk(methodDir)).filter((p) => p.endsWith(".mthds"));
    if (bundlePaths.length === 0) continue;

    const files: MthdsFileItem[] = [];
    const sourceHashes: Record<string, string> = {};
    for (const relative of bundlePaths) {
      const content = await readFile(path.join(methodDir, relative), "utf-8");
      // `source` is the repo-relative path, so a validation error points at a real file.
      const source = `methods/${entry.name}/${relative}`;
      files.push({ content, source });
      sourceHashes[source] = sha256(content);
    }
    methods.push({ name: entry.name, files, sourceHashes });
  }
  return methods;
}

/** What `readGeneratedTree` found on disk — the three cases the callers report differently. */
export type GeneratedTree =
  | { status: "ok"; lockContent: string; files: CodegenTreeFile[]; treePaths: string[] }
  | { status: "no-tree" }
  | { status: "no-lock"; treePaths: string[] };

/**
 * Read one generated tree: its lock, plus every file the check considers.
 *
 * Two of the SDK's caller obligations are discharged here, and both fail as a
 * *wrong verdict* rather than an error if you get them wrong. The walk is
 * recursive from the lock's directory with paths relative to it, because an
 * incomplete list reports a present file as `missing` and hides a stray
 * entirely. And the text is passed exactly as read — reformatting or
 * re-encoding an artifact reports it `hand-edited`.
 *
 * Filtering with the SDK's own `isStampableArtifactPath` is what lets the
 * starter-owned `sources.json` sit beside the lock without being called an orphan.
 */
export async function readGeneratedTree(outDir: string): Promise<GeneratedTree> {
  let treePaths: string[];
  try {
    treePaths = await walk(outDir);
  } catch {
    return { status: "no-tree" };
  }

  let lockContent: string;
  try {
    lockContent = await readFile(path.join(outDir, LOCK_FILENAME), "utf-8");
  } catch {
    return { status: "no-lock", treePaths };
  }

  const files: CodegenTreeFile[] = [];
  for (const relative of treePaths) {
    if (!isStampableArtifactPath(relative)) continue;
    files.push({ path: relative, content: await readFile(path.join(outDir, relative), "utf-8") });
  }
  return { status: "ok", lockContent, files, treePaths };
}
